# Generated by Django 3.0.5 on 2020-04-25 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile_highEdu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('field', models.CharField(max_length=50)),
                ('ofType', models.CharField(max_length=50)),
                ('branch', models.CharField(max_length=50)),
                ('year_join', models.SmallIntegerField()),
                ('year_pass', models.SmallIntegerField()),
                ('score', models.SmallIntegerField()),
                ('state', models.CharField(max_length=50)),
                ('place', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Profile_hsecEdu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('branch', models.CharField(max_length=50)),
                ('year_join', models.SmallIntegerField()),
                ('year_pass', models.SmallIntegerField()),
                ('score', models.SmallIntegerField()),
                ('state', models.CharField(max_length=50)),
                ('place', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Profile_personal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('dob', models.DateField()),
                ('gender', models.CharField(max_length=6)),
                ('mother_name', models.CharField(max_length=50)),
                ('father_name', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=10)),
                ('state', models.CharField(max_length=50)),
                ('place', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=100)),
                ('pincode', models.CharField(max_length=7)),
            ],
        ),
        migrations.CreateModel(
            name='Profile_pro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('role', models.CharField(max_length=50)),
                ('year_join', models.SmallIntegerField()),
                ('state', models.CharField(max_length=50)),
                ('place', models.CharField(max_length=50)),
                ('previous', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Profile_secEdu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=100)),
                ('year_join', models.SmallIntegerField()),
                ('year_pass', models.SmallIntegerField()),
                ('score', models.SmallIntegerField()),
                ('state', models.CharField(max_length=50)),
                ('place', models.CharField(max_length=50)),
            ],
        ),
    ]
