# Generated by Django 3.0.5 on 2020-05-08 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phase1', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('attachment', models.ImageField(upload_to='pics')),
                ('venue', models.CharField(max_length=100)),
                ('date_time', models.CharField(max_length=50)),
                ('to_alumni', models.TextField()),
                ('to_inst', models.TextField()),
            ],
        ),
    ]
