# Generated by Django 3.0.5 on 2020-05-11 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phase1', '0006_foremail'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='email',
            field=models.CharField(default='-', max_length=150),
        ),
    ]
