from django.db import models

# Create your models here.
class Institution(models.Model):
    username = models.CharField(max_length=50)
    institution_name = models.CharField(max_length=100)
    institution_field = models.CharField(max_length=50)
    institution_type = models.CharField(max_length=50)
    alt_email = models.CharField(max_length=150)
    institution_state = models.CharField(max_length=50)
    institution_place = models.CharField(max_length=50)
    institution_pincode = models.CharField(max_length=7)

class EnggClg_Alumni(models.Model):
    person_name = models.CharField(max_length=100)
    person_email = models.CharField(max_length=150)
    person_gender = models.CharField(max_length=6)
    person_phone = models.CharField(max_length=10)
    institution_name = models.CharField(max_length=100)
    institution_branch = models.CharField(max_length=50)
    institution_year_pass = models.SmallIntegerField()
    institution_state = models.CharField(max_length=50)
    institution_place = models.CharField(max_length=50)
    company_name = models.CharField(max_length=100)
    company_role = models.CharField(max_length=50)
    company_year_join = models.SmallIntegerField()
    company_state = models.CharField(max_length=50)
    company_place = models.CharField(max_length=50)
    company_previous = models.TextField()
    accepted = models.BooleanField(default=False)

class EnggUni_Alumni(models.Model):
    person_name = models.CharField(max_length=100)
    person_email = models.CharField(max_length=150)
    person_gender = models.CharField(max_length=6)
    person_phone = models.CharField(max_length=10)
    institution_name = models.CharField(max_length=100)
    institution_branch = models.CharField(max_length=50)
    institution_year_pass = models.SmallIntegerField()
    institution_state = models.CharField(max_length=50)
    institution_place = models.CharField(max_length=50)
    company_name = models.CharField(max_length=100)
    company_role = models.CharField(max_length=50)
    company_year_join = models.SmallIntegerField()
    company_state = models.CharField(max_length=50)
    company_place = models.CharField(max_length=50)
    company_previous = models.TextField()
    accepted = models.BooleanField(default=False)

class MediClg_Alumni(models.Model):
    person_name = models.CharField(max_length=100)
    person_email = models.CharField(max_length=150)
    person_gender = models.CharField(max_length=6)
    person_phone = models.CharField(max_length=10)
    institution_name = models.CharField(max_length=100)
    institution_branch = models.CharField(max_length=50)
    institution_year_pass = models.SmallIntegerField()
    institution_state = models.CharField(max_length=50)
    institution_place = models.CharField(max_length=50)
    company_name = models.CharField(max_length=100)
    company_role = models.CharField(max_length=50)
    company_year_join = models.SmallIntegerField()
    company_state = models.CharField(max_length=50)
    company_place = models.CharField(max_length=50)
    company_previous = models.TextField()
    accepted = models.BooleanField(default=False)

class MediUni_Alumni(models.Model):
    person_name = models.CharField(max_length=100)
    person_email = models.CharField(max_length=150)
    person_gender = models.CharField(max_length=6)
    person_phone = models.CharField(max_length=10)
    institution_name = models.CharField(max_length=100)
    institution_branch = models.CharField(max_length=50)
    institution_year_pass = models.SmallIntegerField()
    institution_state = models.CharField(max_length=50)
    institution_place = models.CharField(max_length=50)
    company_name = models.CharField(max_length=100)
    company_role = models.CharField(max_length=50)
    company_year_join = models.SmallIntegerField()
    company_state = models.CharField(max_length=50)
    company_place = models.CharField(max_length=50)
    company_previous = models.TextField()
    accepted = models.BooleanField(default=False)

class OthClg_Alumni(models.Model):
    person_name = models.CharField(max_length=100)
    person_email = models.CharField(max_length=150)
    person_gender = models.CharField(max_length=6)
    person_phone = models.CharField(max_length=10)
    institution_name = models.CharField(max_length=100)
    institution_branch = models.CharField(max_length=50)
    institution_year_pass = models.SmallIntegerField()
    institution_state = models.CharField(max_length=50)
    institution_place = models.CharField(max_length=50)
    company_name = models.CharField(max_length=100)
    company_role = models.CharField(max_length=50)
    company_year_join = models.SmallIntegerField()
    company_state = models.CharField(max_length=50)
    company_place = models.CharField(max_length=50)
    company_previous = models.TextField()
    accepted = models.BooleanField(default=False)

class OthUni_Alumni(models.Model):
    person_name = models.CharField(max_length=100)
    person_email = models.CharField(max_length=150)
    person_gender = models.CharField(max_length=6)
    person_phone = models.CharField(max_length=10)
    institution_name = models.CharField(max_length=100)
    institution_branch = models.CharField(max_length=50)
    institution_year_pass = models.SmallIntegerField()
    institution_state = models.CharField(max_length=50)
    institution_place = models.CharField(max_length=50)
    company_name = models.CharField(max_length=100)
    company_role = models.CharField(max_length=50)
    company_year_join = models.SmallIntegerField()
    company_state = models.CharField(max_length=50)
    company_place = models.CharField(max_length=50)
    company_previous = models.TextField()
    accepted = models.BooleanField(default=False)