# Generated by Django 3.0.5 on 2020-05-08 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phase2', '0002_engguni_alumni_mediclg_alumni_mediuni_alumni_othclg_alumni_othuni_alumni'),
    ]

    operations = [
        migrations.AddField(
            model_name='enggclg_alumni',
            name='accepted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='engguni_alumni',
            name='accepted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='mediclg_alumni',
            name='accepted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='mediuni_alumni',
            name='accepted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='othclg_alumni',
            name='accepted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='othuni_alumni',
            name='accepted',
            field=models.BooleanField(default=False),
        ),
    ]
